var constants = {
    //// List
    CLEAR: 'Clear',
    FILTER: 'Filter',
    STATUS: 'Status',
    LBL_ISACTIVE: 'IsActive',
    FIRSTNAME: 'First Name',
    LASTNAME: 'Last Name',
    PHONENUMBER: 'Phone Number',
    ALTERNATENUMBER: 'Alternate Number',
    CONTACTNUMBER: 'Contact Number',
    PASSWORD: 'Password',
    CONFIRMPASSWORD: 'Confirm Password',
    PHONE_HEADER: 'Phone',
    NUMBER_HEADER: 'Number',
    POSITION: 'Position',
    NAME: 'Name',
    EMAIL: 'Email',
    EXPERIENCE_HEADER: 'Exp.',
    YEARS_HEADER: 'Yrs.',
    EXPERIENCE_YEARS_HEADER: 'Exp. Yrs.',
    EXPERIENCE_YEARS: 'Experience (Years)',
    DATE_HEADER: 'Date',
    TIME_HEADER: 'Time',
    LBL_ACTIVE: 'Active',
    LBL_INACTIVE: 'Inactive',
    LBL_SHOWING: 'Showing',
    LBL_TO: 'to',
    LBL_OF: 'of',
    LBL_ENTRIES: 'entries',
    STATUS_LABEL: 'StatusLabel',
    LBL_NEW: 'new',
    LBL_ONE: '1',
    EDIT_URL: '/edit',
    APPLICATION_URL: 'application/',
    DATABASE_URL: 'database/',
    DESIGNATION_URL: 'designation/',
    DOMAIN_URL: 'domain/',
    FRAMEWORK_URL: 'framework/',
    LANGUAGE_URL: 'language/',
    OPERATINGSYSTEM_URL: 'operatingSystem/',
    PROJECT_URL: 'project/',
    RESUME_URL: 'resume/',
    PROJECTROLE_URL: 'projectRole/',
    TECHNOLOGY_URL: 'technology/',
    USER_URL: 'user/',
    ROLE_URL: 'role/',

    //// Menu
    RESUME_MANAGEMENT_SYSTEM: 'Resume Management System',
    WELCOME_TO : 'Welcome To',
    ANSI_BYTECODE_LLP : 'Ansi Bytecode LLP',
    HOME: 'Home',
    LOOKUPS: 'Lookups',
    LOGOUT: 'Logout',
    MANAGE_ROLES: 'Manage Roles',
    LOOKUPS_APPLICATION: 'Lookups_Application',
    LOOKUPS_LOOKUPS: 'Lookups_Lookups',
    LOOKUPS_DATABASE: 'Lookups_Database',
    LOOKUPS_DESIGNATION: 'Lookups_Designation',
    LOOKUPS_DOMAIN: 'Lookups_Domain',
    LOOKUPS_FRAMEWORK: 'Lookups_Framework',
    LOOKUPS_LANGUAGE: 'Lookups_Language',
    LOOKUPS_OPERATINGSYSTEM: 'Lookups_OperatingSystem',
    LOOKUPS_PROJECT: 'Lookups_Project',
    LOOKUPS_ROLE: 'Lookups_Role',
    LOOKUPS_TECHNOLOGY: 'Lookups_Technology',
    RESUMELIST_RESUMELIST: 'ResumeList_ResumeList',
    ROLE_ROLE: 'Role_Role',
    ROLE_MANAGEROLES: 'Role_ManageRoles',
    ROLE_ROLEPERMISSIONS: 'Role_RolePermissions',
    ROLE_ASSIGNROLE: 'Role_AssignRole',
    USER_USER: 'User_User',
    USER_MANAGEUSERS: 'User_ManageUsers',
    USER_USERPERMISSIONS: 'User_UserPermissions',

    // login
    LOGIN: 'Login',
    FORGOTPASSWORD: 'Forgot Password',
    FORGOTPASSWORDLINK: 'Forgot Password?',
    CHANGEPASSWORD: 'Change Password',
    OLDPASSWORD: 'Old Password',
    NEWPASSWORD: 'New Password',
    SIGNIN_HEADER: 'Sign in to RMS',
    LOGIN_SUCCESS: 'REQUEST_LOGIN_USER_SUCCESS',
    LOGIN_ERROR: 'REQUEST_LOGIN_USER_ERROR',
    LOGOFF_ERROR: 'REQUEST_LOGOFF_USER',
    CHANGEPASSWORD_SUCCESS: 'REQUEST_CHANGEPASSWORD_SUCCESS',
    CHANGEPASSWORD_ERROR: 'REQUEST_CHANGEPASSWORD_ERROR',
    REQUIRED_OLDPWD_MESSAGE: 'Please enter correct old password',
    FORGOTPASSWORD_SUCCESS: 'REQUEST_FORGOTPASSWORD_SUCCESS',
    FORGOTPASSWORD_ERROR: 'REQUEST_FORGOTPASSWORD_ERROR',
    PWD_SEND_MESSAGE: 'New Password has been sent to your mail account',
    CHANGE_PASSWORD_SUCCESS_MESSAGE: 'Password has been changed successfully',
    USER_STATUS_MESSAGE: 'User is inactive or removed',
    INVALID_EMAIL_MESSAGE: 'Invalid email or password',
    LBLPASSWORD: 'lblPassword',
    LBLCONFIRMPASSWORD: 'lblcnfPassword',
    INPUT_EMAIL: 'inputEmail',
    INPUT_PASSWORD: 'inputPassword',
    INPUT_CONFIRM_PASSWORD: 'inputcnfPassword',
    OLDPASSWORD_LABEL: 'oldpasswordLabel',
    OLDPASSWORD_ERROR: 'oldpasswordError',
    PASSWORDLABEL: 'passwordLabel',
    PASSWORDERROR: 'passwordError',
    CONFIRM_PASSWORD_LABEL: 'confirmPasswordLabel',
    CONFIRM_PASSWORD_ERROR: 'confirmPasswordError',
    LBL_OLDPASSWORD: 'oldpassword',
    LBL_PASSWORD: 'password',
    LBL_CONFIRMPASSWORD: 'confirmPassword',
    EMAIL_LABEL: 'EmailLabel',
    EMAIL_ERROR: 'EmailError',
    PASSWORD_LABEL: 'PasswordLabel',
    PASSWORD_ERROR: 'PasswordError',
    LBL_FORGOTPASSWORDFORM: 'forgotPasswordForm',

    //// Forms
    SAVE: 'Save',
    SAVE_GENERALDETAILS : 'Save General Details',
    GENERAL_DETAILS_SAVED_SUCCESSFULLY :'General Details saved successfully',
    EDIT: 'Edit',
    UPDATE: 'Update',
    DELETE: 'Delete',
    CREATE : 'Create',
    OK: 'Ok',
    OK_STATUS: 'OK',
    CONFLICT: 'Conflict',
    LBL_STARTWAITING: 'startWaiting',
    LBL_STOPWAITING: 'stopWaiting',

    DELETE_CONFIRMATION : 'Are you sure want to delete?',
    SUBMIT: 'Submit',
    CANCEL: 'Cancel',
    INSERT_SUCCESS_MESSAGE : 'Record has been saved successfully',
    UPDATE_SUCCESS_MESSAGE : 'Record has been updated successfully',
    DELETE_SUCCESS_MESSAGE: 'Record has been deleted successfully',
    DELETE_SUCCESS_MESSAGE_MULTIPLE : 'Records have been deleted successfully',
    REQUIRED_MESSAGE: 'Please enter',
    VALIDITY_MESSAGE: 'Please enter valid',
    SELECT_MESSAGE: 'Please select',
    ALTERNATENUMBER_MESSAGE: 'Please enter another phone number',
    MATCH_PASSWORD_MESSAGE: 'Password and Confirm Password does not match',
    PWD_LENGTH_MESSAGE: 'Password must be at least 8 characters long',
    DROPDOWN_PLACEHOLDER: 'Select an option',
    REQUIRED_FILE_MESSAGE: 'Please select file',
    REFERENCE_EXIST_MESSAGE: "The selected record is referred in the application, can't complete delete operation",
    UPDATE_REFERENCE_EXIST_MESSAGE: "Record with same name already exist",

    //// User
    USER: 'User',
    USERS: 'Users',
    MANAGE_USERS: 'Manage Users',
    USER_PERMISSION: 'User Permissions',
    USER_LABEL: 'UserLabel',
    USER_ERROR: 'UserError',
    DDL_USER: 'ddlUser',
    DDL_ROLE: 'ddlRole',
    ROLE_PERMISSION: 'Role Permissions',
    ASSIGN_ROLES: 'Assign Roles',
    NEW_USER: 'New User',
    EDIT_USER: 'Edit User',
    USER_LIST: 'User List',
    RESUME_LIST: 'Resume List',
    EMAIL_EXIST_MESSAGE: 'Email id already exist',
    REGISTERUSER_SUCCESS_MESSAGE: 'User successfully registered',
    FIRST_NAME: 'FirstName',
    FIRSTNAME_LABEL: 'FirstNameLabel',
    FIRSTNAME_ERROR: 'FirstNameError',
    LAST_NAME: 'LastName',
    LASTNAME_LABEL: 'LastNameLabel',
    LASTNAME_ERROR: 'LastNameError',
    CONTACT_NUMBER: 'ContactNumber',
    CONTACTNUMBER_LABEL: 'ContactNumberLabel',
    CONTACTNUMBER_ERROR: 'ContactNumberError',
    CONFIRM_PASSWORD: 'ConfirmPassword',
    CONFIRMPASSWORD_LABEL: 'ConfirmPasswordLabel',
    CONFIRMPASSWORD_ERROR: 'ConfirmPasswordError',
    REQUIRED_CHECKBOX_MESSAGE: 'Please select an option',
    REQUIRED_USER_MESSAGE: 'Please select user',
    REQUIRED_ROLE_MESSAGE: 'Please select role',
    REQUIRED_SELECT_MESSAGE: 'Please select an option',
    LBL_SELECTALL: 'Select All',
    LBL_UNSELECTALL: 'UnSelect All',

    //// Role
    ROLE: 'Role',
    ROLE_EXIST: 'Role already exist',
    ROLE_LIST: 'Role List',
    NEW_ROLE: 'New Role',
    EDIT_ROLE: 'Edit Role',
    ROLENAME: 'RoleName',
    ROLENAME_LABEL: 'RoleNameLabel',
    ROLENAME_ERROR: 'RoleNameError',

    //// Application
    APPLICATION: 'Application',
    APPLICATION_EXIST: 'Application already exist',
    APPLICATION_LIST: 'Application List',
    NEW_APPLICATION: 'New Application',
    EDIT_APPLICATION: 'Edit Application',
    APPLICATIONNAME: 'ApplicationName',
    APPLICATION_DISPLAY_NAME : 'Application',
    APPLICATIONNAME_LABEL: 'ApplicationNameLabel',
    APPLICATIONNAME_ERROR: 'ApplicationNameError',

    //// Database
    DATABASE: 'Database',
    DATABASE_EXIST: 'Database already exist',
    DATABASE_LIST: 'Database List',
    NEW_DATABASE: 'New Database',
    EDIT_DATABASE: 'Edit Database',
    DATABASENAME: 'DatabaseName',
    DATABASENAME_LABEL: 'DatabaseNameLabel',
    DATABASENAME_ERROR: 'DatabaseNameError',

    //// Designation
    DESIGNATION: 'Designation',
    DESIGNATION_EXIST: 'Designation already exist',
    DESIGNATION_LIST: 'Designation List',
    NEW_DESIGNATION: 'New Designation',
    EDIT_DESIGNATION: 'Edit Designation',
    DESIGNATIONNAME: 'DesignationName',
    DESIGNATIONNAME_LABEL: 'DesignationNameLabel',
    DESIGNATIONNAME_ERROR: 'DesignationNameError',

    //// Resume
    RESUME_CREATION : 'Resume Creation',
    GENERAL_DETAILS :'General Details',
    PROJECT_DETAILS : 'Project Details',
    SENTENCE_NOTE : 'Separate the sentences with semicolon(;).',

    //// Domain
    DOMAIN: 'Domain',
    DOMAIN_EXIST: 'Domain already exist',
    DOMAIN_LIST: 'Domain List',
    NEW_DOMAIN: 'New Domain',
    EDIT_DOMAIN: 'Edit Domain',
    DOMAINNAME: 'DomainName',
    DOMAINNAME_LABEL: 'DomainNameLabel',
    DOMAINNAME_ERROR: 'DomainNameError',

    //// Framework
    FRAMEWORK: 'Framework',
    FRAMEWORK_EXIST: 'Framework already exist',
    FRAMEWORK_LIST: 'Framework List',
    NEW_FRAMEWORK: 'New Framework',
    EDIT_FRAMEWORK: 'Edit Framework',
    FRAMEWORKNAME: 'FrameworkName',
    FRAMEWORKNAME_LABEL: 'FrameworkNameLabel',
    FRAMEWORKNAME_ERROR: 'FrameworkNameError',

    //// Language
    LANGUAGE: 'Language',
    LANGUAGE_EXIST: 'Language already exist',
    LANGUAGE_LIST: 'Language List',
    NEW_LANGUAGE: 'New Language',
    EDIT_LANGUAGE: 'Edit Language',
    LANGUAGENAME: 'LanguageName',
    LANGUAGENAME_LABEL: 'LanguageNameLabel',
    LANGUAGENAME_ERROR: 'LanguageNameError',

    //// Operating System
    OPERATINGSYSTEM: 'Operating System',
    OPERATINGSYSTEM_EXIST: 'Operating System already exist',
    OPERATINGSYSTEM_LIST: 'Operating System List',
    NEW_OPERATINGSYSTEM: 'New Operating System',
    EDIT_OPERATINGSYSTEM: 'Edit Operating System',
    OPERATINGSYSTEMNAME: 'OperatingSystemName',
    OPERATINGSYSTEMNAME_LABEL: 'OperatingSystemNameLabel',
    OPERATINGSYSTEMNAME_ERROR: 'OperatingSystemNameError',

    //// Project
    PROJECT: 'Project',
    PROJECT_EXIST: 'Project already exist',
    PROJECT_LIST: 'Project List',
    NEW_PROJECT: 'New Project',
    EDIT_PROJECT: 'Edit Project',
    TEAMSIZE: 'Team Size',
    DESCRIPTION: 'Description',
    OTHERTOOLS: 'Other Tools',
    PROJECTNAME: 'ProjectName',
    PROJECTNAME_LABEL: 'ProjectNameLabel',
    PROJECTNAME_ERROR: 'ProjectNameError',
    TEAM_SIZE: 'TeamSize',
    TEAMSIZE_LABEL: 'TeamSizeLabel',
    TEAMSIZE_ERROR: 'TeamSizeError',
    DESCRIPTION_LABEL: 'DescriptionLabel',
    DESCRIPTION_ERROR: 'DescriptionError',
    OTHER_TOOLS: 'OtherTools',
    OTHERTOOLS_LABEL: 'OtherToolsLabel',
    OTHERTOOLS_ERROR: 'OtherToolsError',
    DOMAIN_LABEL: 'DomainLabel',
    DOMAIN_ERROR: 'DomainError',
    DDL_DOMAIN: 'ddlDomain',
    OPERATING_SYSTEM: 'OperatingSystem',
    OPERATINGSYSTEM_LABEL: 'OperatingSystemLabel',
    OPERATINGSYSTEM_ERROR: 'OperatingSystemError',
    DDL_OPERATINGSYSTEM: 'ddlOperatingSystem',
    DATABASE_LABEL: 'DatabaseLabel',
    DATABASE_ERROR: 'DatabaseError',
    DDL_DATABASE: 'ddlDatabase',
    TECHNOLOGY_LABEL: 'TechnologyLabel',
    TECHNOLOGY_ERROR: 'TechnologyError',
    DDL_TECHNOLOGY: 'dropdownTechnology',
    DROPDOWN_DOMAIN: 'dropdownDomain',
    APPLICATION_LABEL: 'ApplicationLabel',
    APPLICATION_ERROR: 'ApplicationError',
    DROPDOWN_APPLICATION: 'dropdownApplication',
    DROPDOWN_OPERATINGSYSTEM: 'dropdownOperatingSystem',
    FRAMEWORK_LABEL: 'FrameworkLabel',
    DROPDOWN_FRAMEWORK: 'dropdownFramework',
    FRAMEWORK_ERROR: 'FrameworkError',
    LANGUAGE_LABEL: 'LanguageLabel',
    LANGUAGE_ERROR: 'LanguageError',
    DROPDOWN_LANGUAGE: 'dropdownLanguage',
    DROPDOWN_DATABASE: 'dropdownDatabase',
    NEXT: 'Next',
    ADD_PROJECT: 'Add Project',
    SAVE_PROJECT: 'Save Project',
    SAVE_PROJECT_DETAILS: 'Save Project Details',
    PROJECT_ADDED_MESSAGE: 'Project is already added',
    PROJECT_LABEL: 'ProjectLabel',
    PROJECT_ERROR: 'ProjectError',
    ROLE_LABEL: 'RoleLabel',
    ROLE_ERROR: 'RoleError',
    RESPONSIBILITIES: 'Responsibilities',
    RESPONSIBILITIES_LABEL: 'ResponsibilitiesLabel',
    RESPONSIBILITIES_ERROR: 'ResponsibilitiesError',
    TEAM_SIZE_MESSAGE: 'Please enter Team Size between 1 to 99',
    EXPERIENCE_MESSAGE: 'Please enter Experience between 1 to 99',
    PROJECT_COUNT_MESSAGE: 'Please enter Project Count between 1 to 99',

    //// Project Role
    PROJECTROLE: 'Project Role',
    PROJECTROLE_EXIST: 'Project Role already exist',
    PROJECTROLE_LIST: 'Project Role List',
    NEW_PROJECTROLE: 'New Project Role',
    EDIT_PROJECTROLE: 'Edit Project Role',
    PROEJECTROLENAME: 'ProjectRoleName',
    PROEJECTROLENAME_LABEL: 'ProjectRoleNameLabel',
    PROEJECTROLENAME_ERROR: 'ProjectRoleNameError',

    //// Technology
    TECHNOLOGY: 'Technology',
    TECHNOLOGY_EXIST: 'Technology already exist',
    TECHNOLOGY_LIST: 'Technology List',
    NEW_TECHNOLOGY: 'New Technology',
    EDIT_TECHNOLOGY: 'Edit Technology',
    TECHNOLOGYNAME: 'TechnologyName',
    TECHNOLOGYNAME_LABEL: 'TechnologyNameLabel',
    TECHNOLOGYNAME_ERROR: 'TechnologyNameError',

    //// Resume
    RESUME : 'Resume',
    NEW_RESUME : 'New Resume',
    CANDIDATE_NAME : 'Candidate Name',
    EDUCATION_DESCRIPTION :'Education Description',
    CURRENT_COMPANY_NAME : 'Current CompanyName',
    EXPERIENCE : 'Experience',
    PROJECT_COUNT :'Project Count',
    RESUME_EXIST: 'Resume already exist',
    RESUME_CREATE_ERROR_MESSAGE: 'Please enter complete details',
    RESUME_NOT_EXIST : "Resume doesn't exist",
    RESUME_CREATE_SUCCESS_MESSAGE: 'Resume created successfully',
    LBL_CREATE: 'create',
    CANDIDATENAME: 'CandidateName',
    CANDIDATENAME_LABEL: 'CandidateNameLabel',
    CANDIDATENAME_ERROR: 'CandidateNameError',
    EDUCATIONDESCRIPTION: 'EducationDescription',
    EDUCATIONDESCRIPTION_LABEL: 'EducationDescriptionLabel',
    EDUCATIONDESCRIPTION_ERROR: 'EducationDescriptionError',
    CURRENT_COMPANYNAME: 'CurrentCompanyName',
    CURRENT_COMPANYNAME_LABEL: 'CurrentCompanyNameLabel',
    CURRENT_COMPANYNAME_ERROR: 'CurrentCompanyNameError',
    DDL_CURRENTDESIGNATION_LABEL: 'ddlCurrentDesignationLabel',
    DDL_CURRENTDESIGNATION: 'ddlCurrentDesignation',
    DDL_CURRENTDESIGNATION_ERROR: 'ddlCurrentDesignationError',
    EXPERIENCE_LABEL: 'ExperienceLabel',
    EXPERIENCE_ERROR: 'ExperienceError',
    PROJECTCOUNT: 'ProjectCount',
    PROJECTCOUNT_LABEL: 'ProjectCountLabel',
    PROJECTCOUNT_ERROR: 'ProjectCountError',
    KNOWLEDGEDESCRIPTION: 'KnowledgeDescription',
    KNOWLEDGEDESCRIPTION_LABEL: 'KnowledgeDescriptionLabel',
    KNOWLEDGEDESCRIPTION_ERROR: 'KnowledgeDescriptionError',
    WORKDESCRIPTION: 'WorkDescription',
    WORKDESCRIPTION_LABEL: 'WorkDescriptionLabel',
    WORKDESCRIPTION_ERROR: 'WorkDescriptionError',
};

module.exports = constants;