/////Common Actions
export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';

////Candidate Actions
export const GET_CANDIDATES_RESPONSE = 'GET_CANDIDATES_RESPONSE';
export const GET_CANDIDATE_RESPONSE = 'GET_CANDIDATE_RESPONSE';
export const ADD_NEW_CANDIDATE_RESPONSE = 'ADD_NEW_CANDIDATE_RESPONSE';
export const UPDATE_EXISTING_CANDIDATE_RESPONSE = 'UPDATE_EXISTING_CANDIDATE_RESPONSE';
export const DELETE_CANDIDATE_RESPONSE = 'DELETE_CANDIDATE_RESPONSE';

////Application Actions
export const GET_APPLICATION_ALL = 'GET_APPLICATION_ALL';
export const OPEN_ADDAPPLICATION_WINDOW = 'OPEN_ADDAPPLICATION_WINDOW';
export const OPEN_UPDATEAPPLICATION_WINDOW = 'OPEN_UPDATEAPPLICATION_WINDOW';
export const CLOSE_APPLICATION_WINDOW = 'CLOSE_APPLICATION_WINDOW';
export const ADD_NEW_APPLICATION_RESPONSE = 'ADD_NEW_APPLICATION_RESPONSE';
export const UPDATE_EXISTING_APPLICATION_RESPONSE = 'UPDATE_EXISTING_APPLICATION_RESPONSE';
export const DELETE_APPLICATION_RESPONSE = 'DELETE_APPLICATION_RESPONSE';
export const GET_APPLICATION = 'GET_APPLICATION';

/////Resume actions
export const GET_RESUMES_RESPONSE ='GET_RESUMES_RESPONSE';
export const STORE_RESUME_GENERALDETAILS ='STORE_RESUME_GENERALDETAILS';
export const SELECTED_TAB = 'SELECTED_TAB';
export const ADD_PROJECTDETAIL_DIV = 'ADD_PROJECTDETAIL_DIV';
export const GET_RESUME_RESPONSE = 'GET_RESUME_RESPONSE';
export const CLEAR_RESUME_DETAILS = 'CLEAR_RESUME_DETAILS';
export const CLEAR_CANDIDATE_DETAILS = 'CLEAR_CANDIDATE_DETAILS';
export const SET_PROJECTDETAILS = 'SET_PROJECTDETAILS';
export const UPDATE_EXISTING_RESUME_RESPONSE = 'UPDATE_EXISTING_RESUME_RESPONSE';
export const ADD_NEW_RESUME_RESPONSE = 'ADD_NEW_RESUME_RESPONSE';
export const DELETE_RESUME_RESPONSE = 'DELETE_RESUME_RESPONSE';
export const CREATE_RESUME_RESPONSE = 'CREATE_RESUME_RESPONSE';



//// Database Actions
export const GET_DATABASE_ALL = 'GET_DATABASE_ALL';
export const GETALL_ACTIVE_DATABASES = 'GETALL_ACTIVE_DATABASES';
export const OPEN_ADDDATABASE_WINDOW = 'OPEN_ADDDATABASE_WINDOW';
export const OPEN_UPDATEDATABASE_WINDOW = 'OPEN_UPDATEDATABASE_WINDOW';
export const CLOSE_DATABASE_WINDOW = 'CLOSE_DATABASE_WINDOW';
export const ADD_NEW_DATABASE_RESPONSE = 'ADD_NEW_DATABASE_RESPONSE';
export const UPDATE_EXISTING_DATABASE_RESPONSE = 'UPDATE_EXISTING_DATABASE_RESPONSE';
export const DELETE_DATABASE_RESPONSE = 'DELETE_DATABASE_RESPONSE';
export const GET_DATABASE = 'GET_DATABASE';

//// Designation Actions
export const GET_DESIGNATION_ALL = 'GET_DESIGNATION_ALL';
export const OPEN_ADDDESIGNATION_WINDOW = 'OPEN_ADDDESIGNATION_WINDOW';
export const OPEN_UPDATEDESIGNATION_WINDOW = 'OPEN_UPDATEDESIGNATION_WINDOW';
export const CLOSE_DESIGNATION_WINDOW = 'CLOSE_DESIGNATION_WINDOW';
export const ADD_NEW_DESIGNATION_RESPONSE = 'ADD_NEW_DESIGNATION_RESPONSE';
export const UPDATE_EXISTING_DESIGNATION_RESPONSE = 'UPDATE_EXISTING_DESIGNATION_RESPONSE';
export const DELETE_DESIGNATION_RESPONSE = 'DELETE_DESIGNATION_RESPONSE';
export const GET_DESIGNATION = 'GET_DESIGNATION';

//// Domain Actions
export const GET_DOMAIN_ALL = 'GET_DOMAIN_ALL';
export const GETALL_ACTIVE_DOMAINS = 'GETALL_ACTIVE_DOMAINS';
export const OPEN_ADDDOMAIN_WINDOW = 'OPEN_ADDDOMAIN_WINDOW';
export const OPEN_UPDATEDOMAIN_WINDOW = 'OPEN_UPDATEDOMAIN_WINDOW';
export const CLOSE_DOMAIN_WINDOW = 'CLOSE_DOMAIN_WINDOW';
export const ADD_NEW_DOMAIN_RESPONSE = 'ADD_NEW_DOMAIN_RESPONSE';
export const UPDATE_EXISTING_DOMAIN_RESPONSE = 'UPDATE_EXISTING_DOMAIN_RESPONSE';
export const DELETE_DOMAIN_RESPONSE = 'DELETE_DOMAIN_RESPONSE';
export const GET_DOMAIN = 'GET_DOMAIN';

//// Framework Actions
export const GET_FRAMEWORK_ALL = 'GET_FRAMEWORK_ALL';
export const OPEN_ADDFRAMEWORK_WINDOW = 'OPEN_ADDFRAMEWORK_WINDOW';
export const OPEN_UPDATEFRAMEWORK_WINDOW = 'OPEN_UPDATEFRAMEWORK_WINDOW';
export const CLOSE_FRAMEWORK_WINDOW = 'CLOSE_FRAMEWORK_WINDOW';
export const ADD_NEW_FRAMEWORK_RESPONSE = 'ADD_NEW_FRAMEWORK_RESPONSE';
export const UPDATE_EXISTING_FRAMEWORK_RESPONSE = 'UPDATE_EXISTING_FRAMEWORK_RESPONSE';
export const DELETE_FRAMEWORK_RESPONSE = 'DELETE_FRAMEWORK_RESPONSE';
export const GET_FRAMEWORK = 'GET_FRAMEWORK';

//// Language Actions
export const GET_LANGUAGE_ALL = 'GET_LANGUAGE_ALL';
export const OPEN_ADDLANGUAGE_WINDOW = 'OPEN_ADDLANGUAGE_WINDOW';
export const OPEN_UPDATELANGUAGE_WINDOW = 'OPEN_UPDATELANGUAGE_WINDOW';
export const CLOSE_LANGUAGE_WINDOW = 'CLOSE_LANGUAGE_WINDOW';
export const ADD_NEW_LANGUAGE_RESPONSE = 'ADD_NEW_LANGUAGE_RESPONSE';
export const UPDATE_EXISTING_LANGUAGE_RESPONSE = 'UPDATE_EXISTING_LANGUAGE_RESPONSE';
export const DELETE_LANGUAGE_RESPONSE = 'DELETE_LANGUAGE_RESPONSE';
export const GET_LANGUAGE = 'GET_LANGUAGE';

//// Operating System Actions
export const GET_OPERATINGSYSTEM_ALL = 'GET_OPERATINGSYSTEM_ALL';
export const GETALL_ACTIVE_OPERATINGSYSTEMS = 'GETALL_ACTIVE_OPERATINGSYSTEMS';
export const OPEN_ADDOPERATINGSYSTEM_WINDOW = 'OPEN_ADDOPERATINGSYSTEM_WINDOW';
export const OPEN_UPDATEOPERATINGSYSTEM_WINDOW = 'OPEN_UPDATEOPERATINGSYSTEM_WINDOW';
export const CLOSE_OPERATINGSYSTEM_WINDOW = 'CLOSE_OPERATINGSYSTEM_WINDOW';
export const ADD_NEW_OPERATINGSYSTEM_RESPONSE = 'ADD_NEW_OPERATINGSYSTEM_RESPONSE';
export const UPDATE_EXISTING_OPERATINGSYSTEM_RESPONSE = 'UPDATE_EXISTING_OPERATINGSYSTEM_RESPONSE';
export const DELETE_OPERATINGSYSTEM_RESPONSE = 'DELETE_OPERATINGSYSTEM_RESPONSE';
export const GET_OPERATINGSYSTEM = 'GET_OPERATINGSYSTEM';

//// Project Actions
export const GET_PROJECT_ALL = 'GET_PROJECT_ALL';
export const GETALL_ACTIVE_PROJECTS = 'GETALL_ACTIVE_PROJECTS';
export const OPEN_ADDPROJECT_WINDOW = 'OPEN_ADDPROJECT_WINDOW';
export const OPEN_UPDATEPROJECT_WINDOW = 'OPEN_UPDATEPROJECT_WINDOW';
export const CLOSE_PROJECT_WINDOW = 'CLOSE_PROJECT_WINDOW';
export const ADD_NEW_PROJECT_RESPONSE = 'ADD_NEW_PROJECT_RESPONSE';
export const UPDATE_EXISTING_PROJECT_RESPONSE = 'UPDATE_EXISTING_PROJECT_RESPONSE';
export const DELETE_PROJECT_RESPONSE = 'DELETE_PROJECT_RESPONSE';
export const GET_PROJECT = 'GET_PROJECT';

//// Project Role Actions
export const GET_PROJECTROLE_ALL = 'GET_PROJECTROLE_ALL';
export const OPEN_ADDPROJECTROLE_WINDOW = 'OPEN_ADDPROJECTROLE_WINDOW';
export const OPEN_UPDATEPROJECTROLE_WINDOW = 'OPEN_UPDATEPROJECTROLE_WINDOW';
export const CLOSE_PROJECTROLE_WINDOW = 'CLOSE_PROJECTROLE_WINDOW';
export const ADD_NEW_PROJECTROLE_RESPONSE = 'ADD_NEW_PROJECTROLE_RESPONSE';
export const UPDATE_EXISTING_PROJECTROLE_RESPONSE = 'UPDATE_EXISTING_PROJECTROLE_RESPONSE';
export const DELETE_PROJECTROLE_RESPONSE = 'DELETE_PROJECTROLE_RESPONSE';
export const GET_PROJECTROLE = 'GET_PROJECTROLE';

//// Role Actions
export const GET_ROLE_ALL = 'GET_ROLE_ALL';
export const GETALL_ACTIVE_ROLES = 'GETALL_ACTIVE_ROLES';
export const OPEN_ADDROLE_WINDOW = 'OPEN_ADDROLE_WINDOW';
export const OPEN_UPDATEROLE_WINDOW = 'OPEN_UPDATEROLE_WINDOW';
export const CLOSE_ROLE_WINDOW = 'CLOSE_ROLE_WINDOW';
export const ADD_NEW_ROLE_RESPONSE = 'ADD_NEW_ROLE_RESPONSE';
export const UPDATE_EXISTING_ROLE_RESPONSE = 'UPDATE_EXISTING_ROLE_RESPONSE';
export const DELETE_ROLE_RESPONSE = 'DELETE_ROLE_RESPONSE';
export const GET_ROLE = 'GET_ROLE';

//// Technology Actions
export const GET_TECHNOLOGY_ALL = 'GET_TECHNOLOGY_ALL';
export const GETALL_ACTIVE_TECHNOLOGIES = 'GETALL_ACTIVE_TECHNOLOGIES';
export const OPEN_ADDTECHNOLOGY_WINDOW = 'OPEN_ADDTECHNOLOGY_WINDOW';
export const OPEN_UPDATETECHNOLOGY_WINDOW = 'OPEN_UPDATETECHNOLOGY_WINDOW';
export const CLOSE_TECHNOLOGY_WINDOW = 'CLOSE_TECHNOLOGY_WINDOW';
export const ADD_NEW_TECHNOLOGY_RESPONSE = 'ADD_NEW_TECHNOLOGY_RESPONSE';
export const UPDATE_EXISTING_TECHNOLOGY_RESPONSE = 'UPDATE_EXISTING_TECHNOLOGY_RESPONSE';
export const DELETE_TECHNOLOGY_RESPONSE = 'DELETE_TECHNOLOGY_RESPONSE';
export const GET_TECHNOLOGY = 'GET_TECHNOLOGY';

//// User Actions
export const GET_USER_ALL = 'GET_USER_ALL';
export const GETALL_ACTIVE_USERS = 'GETALL_ACTIVE_USERS';
export const OPEN_ADDUSER_WINDOW = 'OPEN_ADDUSER_WINDOW';
export const OPEN_UPDATEUSER_WINDOW = 'OPEN_UPDATEUSER_WINDOW';
export const CLOSE_USER_WINDOW = 'CLOSE_USER_WINDOW';
export const ADD_NEW_USER_RESPONSE = 'ADD_NEW_USER_RESPONSE';
export const UPDATE_EXISTING_USER_RESPONSE = 'UPDATE_EXISTING_USER_RESPONSE';
export const DELETE_USER_RESPONSE = 'DELETE_USER_RESPONSE';
export const GET_USER = 'GET_USER';

//// Permission Module Actions
export const GET_PERMISSIONMODULE_ALL = 'GET_PERMISSIONMODULE_ALL';

//// User Permission Actions
export const GET_USERPERMISSION = 'GET_USERPERMISSION';
export const ADD_NEW_USERPERMISSION_RESPONSE = 'ADD_NEW_USERPERMISSION_RESPONSE';

//// Role Permission Actions
export const GET_ROLEPERMISSION = 'GET_ROLEPERMISSION';
export const ADD_NEW_ROLEPERMISSION_RESPONSE = 'ADD_NEW_ROLEPERMISSION_RESPONSE';

//// User Role Actions
export const GET_USERROLE = 'GET_USERROLE';
export const ADD_NEW_USERROLE_RESPONSE = 'ADD_NEW_USERROLE_RESPONSE';

//// Login Actions
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const CHANGEPASSWORD_RESPONSE = 'CHANGEPASSWORD_RESPONSE';
export const FORGOTPASSWORD_RESPONSE = 'FORGOTPASSWORD_RESPONSE';